### ISSUE TITLE
Why is not Build?

### ISSUE THREAD

**Issue by NVSProgrammer** [tmk907/RacingCarsController#2]
I can not find the exe of the project

**Comment by tmk907** [comment]
WinUI does not have exe file that you can launch. But there is msix installer, that will install application.
[https://github.com/tmk907/RacingCarsController/releases/tag/desktop-v1.1.0](https://github.com/tmk907/RacingCarsController/releases/tag/desktop-v1.1.0)

Installation instructions:

Install certificate:
double click .cer file
click 'Install certificate'
choose 'Local computer'
select certificate store: "Trusted People" or "Trusted Publishers Certification Authorities"
Install RacingCarsController.msix
