### ISSUE TITLE
Certificate is expired

### ISSUE THREAD

**Issue by manutorre** [tmk907/RacingCarsController#3]
I have not been able to install the msix and I think that the reason is that the .cer seems to be expired. Is there a way to install it without it? thanks in advanced

**Comment by tmk907** [comment]
I published application in Microsoft Store [https://apps.microsoft.com/detail/9N8MXSKCDF9J](https://apps.microsoft.com/detail/9N8MXSKCDF9J?cid=github&mode=full)
